name: MapStruct
title: Creating Bean Mappings the Easy Way
org: Gunnar Morling
google_analytics: UA-41136939-1
google_analytics_anonymize: true
disqus: mapstruct
disqus_generate_id: true

profiles:
  development:
    base_url: http://localhost:4242
    disqus_developer: true
  production:
    base_url: http://mapstruct.org
    deploy:
      host: github_pages
      branch: gh-pages
      repository: upstream
