name: MapStruct
title: Creating Bean Mappings the Easy Way
org: Gunnar Morling
google_analytics: UA-41136939-1
google_analytics_anonymize: true
disqus: mapstruct
disqus_generate_id: true

mapstruct_latest_version: 1.1.0.Final
mapstruct_latest_date: November 18th 2016

profiles:
  development:
    base_url: http://localhost:9009
    disqus_developer: true
  production:
    base_url: http://mapstruct.org
    deploy:
      host: github_pages
      branch: gh-pages
      repository: upstream
